micronaut:
  application:
    name: mnFundingJdbc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mn-funding
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
    schema-generate: NONE
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: false
