micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretWithANewOneBeforeCommitAddaptedForLength
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret} # secret
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret} # secret
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
# micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "com.learning.broker.persistence"
    properties:
      hibernate:
        show_sql: false
