micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretWithANewOneBeforeCommitAddaptedForLength
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret} # secret
      schemas: mn
      default-schema: mn
